Algoritmo "atividade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/11/2021
Var
    m1, m2: inteiro


Inicio
 escreva ("informe um valor ")
 leia (m1)
 escreva ("informe um valor ")
 leia (m2)
 se(m1 > 2m) entao
 
           escreva (m1," e o numero maior!")
           senao
           escreva(m2," e o numero maior!")
           
 fimse
Fimalgoritmo